# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12L89ciLMoQmPI8PJjNOw0o3QBbeI1dpF
"""

# --------------------------------------------------------------------------
# Tool for Hemodynamics Inventory Management
# Created to solve the mess of manual PDF lookups in the Cath Lab.
#
# Author: Iván Francisco Sánchez Loredo
# --------------------------------------------------------------------------

import pdfplumber
import re
import os
import unicodedata
from openpyxl import load_workbook
from datetime import datetime

# Global dictionary to track high-value medical assets during the current work session.
# This helps the user get a quick count without opening the Excel file.
session_stats = {"BALONES": 0, "STENTS": 0}

def normalize_text(text):
    """
    Standardizes input by removing Spanish accents and forcing uppercase.
    I implemented this because medical staff might type 'balon' instead of 'balón',
    and the search must be resilient to these variations.
    """
    if not text: return ""
    text = text.upper()
    return ''.join(c for c in unicodedata.normalize('NFD', text)
                  if unicodedata.category(c) != 'Mn')

def load_insabi_catalog(pdf_path):
    """
    Core ETL process: Extracts and flattens PDF tables.
    The PDF structure often splits product names and models into different columns.
    By merging the entire row into a single string, I ensure the search engine
    can match terms regardless of their column position.
    """
    catalog_data = []
    if not os.path.exists(pdf_path):
        print(f"Error de Archivo: No se encontró '{pdf_path}' en el directorio.")
        return []

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            table = page.extract_table()
            if not table: continue
            for row in table:
                # Joining columns into a unified text block to fix PDF fragmentation issues.
                raw_content = " ".join([str(cell).replace('\n', ' ') for cell in row if cell])
                searchable_content = normalize_text(raw_content)

                # Identifying valid rows using the official INSABI code pattern (060.XXX.XXXX).
                insabi_match = re.findall(r'060\.\d{3}\.\d{4}', raw_content)
                if insabi_match:
                    # In this specific catalog, the 'Partida' number is usually the last valid integer.
                    partida = row[-1].strip() if row[-1] and str(row[-1]).strip().isdigit() else "S/P"
                    catalog_data.append({
                        "insabi": insabi_match[0],
                        "partida": partida,
                        "display_text": raw_content,
                        "search_text": searchable_content
                    })
    return catalog_data

def save_to_inventory_excel(data_row):
    """
    Automates the final logging into the vendor's tracking spreadsheet.
    It performs a dynamic row search to find the first empty slot, ensuring no data is overwritten.
    """
    file_path = "CONSUMOS ARTIMEDICA SLP.xlsx"
    if not os.path.exists(file_path):
        print("Error de Excel: No se encontró el archivo de registro.")
        return

    wb = load_workbook(file_path)
    ws = wb.active
    # Find the next available row in Column 1.
    next_row = 2
    while ws.cell(row=next_row, column=1).value is not None:
        next_row += 1

    for col, value in enumerate(data_row, start=1):
        ws.cell(row=next_row, column=col).value = value

    wb.save(file_path)
    print(f"Base de Datos Actualizada: Registrado con éxito en la fila {next_row}")

# --- APPLICATION WORKFLOW ---

print("Iniciando Sistema: Sincronizando Base de Datos de Hemodinamia...")
catalog = load_insabi_catalog("Códigos INSABI (1).pdf")

if catalog:
    print(f"Sistema Listo: {len(catalog)} códigos oficiales INSABI indexados.")

    while True:
        print("\n" + "="*60)
        user_input = input("Buscar Dispositivo (ej: JR4, JL4, Stent) o 'resumen'/'salir': ")

        if user_input.lower() == 'salir': break

        if user_input.lower() == 'resumen':
            print("\n--- RESUMEN DE FIN DE TURNO (Material Externo) ---")
            print(f"Total de Balones registrados: {session_stats['BALONES']}")
            print(f"Total de Stents registrados:  {session_stats['STENTS']}")
            continue

        clean_input = normalize_text(user_input)
        # Tokenizing input to handle mixed alphanumeric codes like 'JR4' or 'JL 3.5'.
        query_tokens = re.findall(r'[A-Z]+|\d+\.\d+|\d+', clean_input)

        matches = []
        for item in catalog:
            source = item['search_text']
            is_match = True

            for token in query_tokens:
                if token.isdigit():
                    # Precision Regex: Ensures '4' matches '4' but NOT '4.5' or '4 to 5' (ranges).
                    # This was a critical fix for catheter sizing accuracy.
                    decimal_pattern = r'(?<![\d\.])' + re.escape(token) + r'(?![\d\.])'
                    range_pattern = re.escape(token) + r'\s*(A|AL|-)\s*\d+'

                    if not re.search(decimal_pattern, source) or re.search(range_pattern, source):
                        is_match = False
                        break
                elif token not in source:
                    is_match = False
                    break

            if is_match:
                matches.append(item)

        if matches:
            print(f"\nResultados de Búsqueda ({len(matches)} coincidencias):")
            for idx, m in enumerate(matches[:5]): # Limiting display to top 5 for UX.
                print(f"{idx+1}. PARTIDA: {m['partida']} | INSABI: {m['insabi']}")
                print(f"   Detalle Completo: {m['display_text'][:115]}...")

            selection = input("\nSelecciona el número de item (o Enter para buscar de nuevo): ")
            if not selection.isdigit() or int(selection) > len(matches): continue

            selected = matches[int(selection)-1]
            print(f"\n[!] DATOS DE FACTURACIÓN: PARTIDA {selected['partida']} | INSABI {selected['insabi']}")

            # Filtering logic: Only High-Cost devices (Balloons/Stents) require Excel logging.
            is_balon = "BALON" in clean_input
            is_stent = "STENT" in clean_input

            if is_balon or is_stent:
                if input("\n¿Es material externo para registro? (si/no): ").lower() == "si":
                    dr_name = input("Médico Tratante: ")
                    ref_num = input("Número de Referencia (REF): ")
                    remission = input("Folio de Remisión: ")
                    lot_num = input("Número de Lote: ")
                    exp_date = input("Fecha de Caducidad (DD/MM/YYYY): ")

                    # Structuring data for the Artimedica SLP master template.
                    excel_row = [1, user_input.upper(), datetime.now().strftime("%d/%m/%Y"),
                                dr_name, ref_num, remission, lot_num, "", exp_date, ""]

                    save_to_inventory_excel(excel_row)

                    # Syncing session counters.
                    if is_balon: session_stats['BALONES'] += 1
                    if is_stent: session_stats['STENTS'] += 1
        else:
            print("Artículo no encontrado. Intenta con el modelo específico (ej: 'JR4').")
